<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Rahee-Khan" failures="1" tests="1" name="Test_E2E_05_iOS" time="88.731" errors="0" timestamp="2023-11-13T16:17:43 EST">
  <testcase classname="mobile_tests.BankingApplicationPaymentTests" name="verify_user_making_payment" time="19.447">
    <failure type="java.lang.AssertionError" message="Amount has not been deducted. did not expect [35000] but found [35000]">
      <![CDATA[java.lang.AssertionError: Amount has not been deducted. did not expect [35000] but found [35000]
at mobile_tests.BankingApplicationPaymentTests.verify_user_making_payment(BankingApplicationPaymentTests.java:86)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- verify_user_making_payment -->
</testsuite> <!-- Test_E2E_05_iOS -->
